name: Neon Schema Diff GitHub Action
description:
  Create GitHub Pull Request comments with the schema diff with the parent
  branch
author: Neon Database
branding:
  icon: align-left
  color: green
inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    required: false
    default: ${{ github.token }}
  project_id:
    description: The project id
    required: true
  branch_name:
    description: The branch name
    required: false
  api_key:
    description: The Neon API key
    required: true
  api_host:
    description: The Neon API Host
    default: https://console.neon.tech/api/v2
  username:
    description: The db role name
    default: neondb_owner
  database:
    description: The database name
    default: neondb
outputs:
  schemadiff:
    description: The schema diff SQL patch
  comment_url:
    description: The url of the comment containing the schema diff
runs:
  using: node20
  main: dist/index.js
